disabled_rules: # rule identifiers to exclude from running
  - private_over_fileprivate #prefered to reduce the complexity of a class and have the ability to add private structures to only this class/ file
  - file_length
  - unused_closure_parameter

# parameterized rules can be customized from this point
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_top_level_acl
  - fatal_error_message
  - file_name

#setup trailing whitespaces only for code and not for empty lines
trailing_whitespace: 
  ignores_empty_lines: true
  ignores_comments: true

cyclomatic_complexity:
  ignores_case_statements: true

#accept two lines of whitespace
vertical_whitespace:
  max_empty_lines: 2


line_length:
  - 160
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error

