disabled_rules: # rule identifiers to exclude from running
  - private_over_fileprivate #prefered to reduce the complexity of a class and have the ability to add private structures to only this class/ file
 # - vertical_whitespace
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - valid_docs
#  - variable_name
#  - variable_name_min_length
#  - variable_name_max_length
# parameterized rules can be customized from this configuration file

opt_in_rules:

#setup trailing whitespaces only for code and not for empty lines
trailing_whitespace: 
  ignores_empty_lines: true
  ignores_comments: true

#accept two lines of whitespace
vertical_whitespace:
  max_empty_lines: 2


line_length:
  - 160
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 30 # warning
  - 40 # error
variable_name_min_length:
  - 2 # warning
  - 1 # error